#!/bin/bash

# docker-machine ssh netvor "rm -rf ~/Apps/niceminer" > /dev/null
# docker-machine scp -r ../nicehashstats dev@netvor:~/Apps/niceminer > /dev/null
# docker-machine ssh netvor "cd ~/Apps/niceminer && python3.5 -u run.py"
# docker-machine ssh netvor "cd ~/Apps/niceminer && python3.5 -u run.py > logs/log-$(date +"%Y%m%d_%H_%M_%S").txt"

# python3.5 -u run.py > ./logs/log-$(date +"%Y%m%d_%H_%M_%S").txt
# ssh miner@192.168.1.106
# ssh miner@192.168.1.106 "rm -rf ~/apps/niceminer"
# scp -r ../niceminer miner@192.168.1.106:~/apps/niceminer

rsync -uav  --delete --exclude '.git/' --exclude '*.pyc' ../niceminer miner@rig2:~/apps
ssh miner@rig2 "cd ~/apps/niceminer && python3.5 -u run.py"

# python3.5 -u run.py > ./logs/log-$(date +"%Y%m%d_%H_%M_%S").txt